// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


import Link from "next/dist/client/link";
import "./globals.css"; // Wajib ada agar Tailwind CSS bekerja

export const metadata = {
  title: "rAthena Control Panel",
  description: "Web Interface untuk Server rAthena",
};

export default function RootLayout({
  children, // 'children' ini adalah titipan dari page.tsx (lukisannya)
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="id">
      {/* TIGA MAGIC CLASS TAILWIND UNTUK STICKY FOOTER:
        1. min-h-screen: Memaksa tinggi halaman minimal sama dengan tinggi layar monitor.
        2. flex: Mengaktifkan mode Flexbox.
        3. flex-col: Menyusun elemen dari atas ke bawah (Header -> Main -> Footer).
      */}
      <body className="min-h-screen flex flex-col bg-slate-50 text-slate-800 font-sans">
        
        {/* --- HEADER --- */}
        <header className="bg-indigo-600 text-white shadow-md">
          {/* max-w-5xl mx-auto: Menahan lebar maksimal agar tidak terlalu melar di monitor besar, dan ditaruh di tengah */}
          <div className="max-w-5xl mx-auto px-6 py-4 flex justify-between items-center">
            <h1 className="text-2xl font-bold tracking-wide">rAthena Panel</h1>
            <nav>
              <ul className="flex space-x-6 text-sm font-medium">
                {/* <li><a href="/" className="hover:text-indigo-200 transition">Home</a></li> */}
                <li><Link href="/" className="hover:text-indigo-200 transition">Home</Link></li>
                <li><Link href="/ranking" className="hover:text-indigo-200 transition">Ranking</Link></li>
                {/* <li><a href="#" className="hover:text-indigo-200 transition">Daftar Akun</a></li> */}
              </ul>
            </nav>
          </div>
        </header>

        {/* --- MAIN BODY (Konten Utama) --- */}
        {/* flex-grow: Sangat penting! Ini akan mendorong Footer ke paling bawah layar jika isi body sedikit */}
        <main className="flex-grow w-full max-w-5xl mx-auto px-6 py-8">
          {children} 
        </main>

        {/* --- FOOTER --- */}
        <footer className="bg-slate-800 text-slate-300 py-6 text-center text-sm">
          <p>&copy; {new Date().getFullYear()} rAthena Server. All rights reserved.</p>
        </footer>

      </body>
    </html>
  );
}